# -*- coding: utf-8 -*-
"""22428645_AGBANU RAPHAEL EDEM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UjUWj-rzm-Dyba2Vy8BPueQ5WMVYQE8H
"""

#Name: AGBANU RAPHAEL EDEM
#ID: 22428645

import networkx as nx
import matplotlib.pyplot as plt

# Create graph
G = nx.Graph()

# Add edges to match degree distribution 4,3,2,1,1,0
edges = [
    ('Edem', 'Priscilla'),
    ('Edem', 'Philip'),
    ('Edem', 'Gilbert'),
    ('Edem', 'Mark'),
    ('Priscilla', 'Philip'),
    ('Priscilla', 'Gilbert')
]

G.add_edges_from(edges)

# Add isolated node
G.add_node('Lydia')

# Compute metrics
print("Number of nodes:", G.number_of_nodes())
print("Number of edges:", G.number_of_edges())
print("Degree distribution:", dict(G.degree()))
print("Isolated nodes:", list(nx.isolates(G)))

# Draw
plt.figure(figsize=(6,4))
pos = nx.spring_layout(G)
nx.draw(G, pos, with_labels=True, node_size=1500, font_size=10)
plt.show()